insert into album (id,name,artist,genre,year) values(1,'Thriller','Michael Jackson','Pop',1982);
insert into album (id,name,artist,genre,year) values(2,'Singles','Future Islands','Indie',2014);
insert into album (id,name,artist,genre,year) values(3,'This Is Happening','LCD Soundsystem','Dance',2010);
insert into album (id,name,artist,genre,year) values(4,'Disappear Here','Bad Suns','Rock',2016);
insert into album (id,name,artist,genre,year) values(5,'ANTI','Rihanna','Hip hop',2016);
insert into album (id,name,artist,genre,year) values(6,'Straight, No Chaser','Thelonius Monk','Jazz',1967);
insert into album (id,name,artist,genre,year) values(7,'OK Computer','Radiohead','Alternative',1997);
insert into album (id,name,artist,genre,year) values(8,'Running On Empty','Jackson Browne','Country',1977);
insert into album (id,name,artist,genre,year) values(9,'Don壽猼 Believe the Truth','Oasis','Alternative',2005);
insert into album (id,name,artist,genre,year) values(10,'Whenever You Need Somebody','Rick Astley','Pop',1987);
insert into album (id,name,artist,genre,year) values(11,'Christopher Cross','Christopher Cross','Yacht Rock',1979);
insert into album (id,name,artist,genre,year) values(12,'All Things Must Pass','George Harrison','Rock',1970);
insert into album (id,name,artist,genre,year) values(13,'Dear Science','TV on the Radio','Alternative',2008);
insert into album (id,name,artist,genre,year) values(14,'Blackstar','David Bowie','Rock',2016);
insert into album (id,name,artist,genre,year) values(15,'How to Save A Life','The Fray','Pop',2005);
insert into album (id,name,artist,genre,year) values(16,'The Life of Pablo','Kanye West','Hip hop',2016);
insert into album (id,name,artist,genre,year) values(17,'Moanin in the Moonlight','Howlin Wolf','Blues',1958);
insert into album (id,name,artist,genre,year) values(18,'Ah Um','Charles Mingus','Jazz',1959);
insert into album (id,name,artist,genre,year) values(19,'Eyes Open','Snow Patrol','Pop',2006);
insert into album (id,name,artist,genre,year) values(20,'What We Live For','American Authors','Rock',2016);
insert into album (id,name,artist,genre,year) values(21,'I Never Loved A Man the Way I Love You','Aretha Franklin','Soul',1967);
insert into album (id,name,artist,genre,year) values(22,'Pickin Up the Pieces','Fitz & the Tantrums','Dance',2010);
insert into album (id,name,artist,genre,year) values(23,'Little Seeds','Shovels & Rope','Folk',2016);
insert into album (id,name,artist,genre,year) values(24,'Purple Rain','Prince','Pop',1984);
insert into album (id,name,artist,genre,year) values(25,'Abbey Road','The Beatles','Rock',1969);
insert into album (id,name,artist,genre,year) values(26,'Sigh No More','Mumford & Sons','Alternative',2009);
insert into album (id,name,artist,genre,year) values(27,'Bon Iver','Bon Iver','Indie',2011);
insert into album (id,name,artist,genre,year) values(28,'Dig Your Own Hole','Chemical Brothers','Electronica',1997);
insert into album (id,name,artist,genre,year) values(29,'The Man Who','Travis','Alternative',1999);
insert into album (id,name,artist,genre,year) values(30,'Texas Flood','Stevie Ray Vaughan','Blues',1983);
insert into album (id,name,artist,genre,year) values(31,'Coming Home','Leon Bridges','Soul',2016);
insert into album (id,name,artist,genre,year) values(32,'Moon Safari','Air','Electronica',1998);
insert into album (id,name,artist,genre,year) values(33,'Crazysexycool','TLC','R&B',1994);
insert into album (id,name,artist,genre,year) values(34,'The Queen Is Dead','The Smiths','Alternative',1986);
insert into album (id,name,artist,genre,year) values(35,'Walking on a Dream','Emprie of the Sun','Dance',2009);
insert into album (id,name,artist,genre,year) values(36,'Straight Outta Compton','N.W.A.','Rap',1988);
insert into album (id,name,artist,genre,year) values(37,'The Luxury Gap','Heaven 17','New Wave',1982);
insert into album (id,name,artist,genre,year) values(38,'Please Please Me','The Beatles','Rock',1963);
insert into album (id,name,artist,genre,year) values(39,'Minute to Midnight','Linkin Park','Rock',2007);
insert into album (id,name,artist,genre,year) values(40,'Bad Blood','Bastille','Alternative',2013);
insert into album (id,name,artist,genre,year) values(41,'The Harder They Come','Jimmy Cliff','Reggae',1972);
insert into album (id,name,artist,genre,year) values(42,'There is Nothing Left to Lose','Foo Fighters','Alternative',1999);
insert into album (id,name,artist,genre,year) values(43,'Tommy','The Who','Rock',1969);
insert into album (id,name,artist,genre,year) values(44,'Goodbye Yellow Brick Road','Elton John','Rock',1973);
insert into album (id,name,artist,genre,year) values(45,'Every Picture Tells A Story','Rod Stewart','Rock',1971);
insert into album (id,name,artist,genre,year) values(46,'I''m Alright','Jo Dee Messina','Country',1998);
insert into album (id,name,artist,genre,year) values(47,'Closer','Joy Division','Alternative',1980);
insert into album (id,name,artist,genre,year) values(48,'Power, Corruption, Lies','New Order','New Wave',1983);
insert into album (id,name,artist,genre,year) values(49,'This is Not a Test!','Missy Elliott','Rap',2003);
insert into album (id,name,artist,genre,year) values(50,'The Downward Spiral','Nine Inch Nails','Alternative',1994);
insert into album (id,name,artist,genre,year) values(51,'Mezzanine','Massive Attack','Alternative',1998);
insert into album (id,name,artist,genre,year) values(52,'Whitney Houston','Whitney Houston','Pop',1985);
insert into album (id,name,artist,genre,year) values(53,'Tourist History','Two Door Cinema Club','Dance',2010);
insert into album (id,name,artist,genre,year) values(54,'Parklife','Blur','Alternative',1994);
insert into album (id,name,artist,genre,year) values(55,'New York Dolls','New York Dolls','Rock',1973);
insert into album (id,name,artist,genre,year) values(56,'Come Clean','Curve','Alternative',1998);
insert into album (id,name,artist,genre,year) values(57,'Midnite Vultures','Beck','Alternative',1999);
insert into album (id,name,artist,genre,year) values(58,'The Shepherd''s Dog','Iron & Wine','Folk',2007);
insert into album (id,name,artist,genre,year) values(59,'Ten','Pearl Jam','Alternative',1991);
insert into album (id,name,artist,genre,year) values(60,'IV','Led Zeppelin','Rock',1971);
insert into album (id,name,artist,genre,year) values(61,'Permanent Vacation','Aerosmith','Rock',1987);
insert into album (id,name,artist,genre,year) values(62,'This Empty Northern Hemisphere','Gregory Alan Isakov','Folk',2009);
insert into album (id,name,artist,genre,year) values(63,'Exodus','Bob Marley','Reggae',1977);
insert into album (id,name,artist,genre,year) values(64,'Souvlaki','Slowdive','Shoegaze',1993);
insert into album (id,name,artist,genre,year) values(65,'Definitely Maybe','Oasis','Alternative',1994);
insert into album (id,name,artist,genre,year) values(66,'Margerine Eclipse','Stereolab','Indie',2004);
insert into album (id,name,artist,genre,year) values(67,'Kind of Blue','Miles Davis','Jazz',1959);
insert into album (id,name,artist,genre,year) values(68,'News of the World','Queen','Rock',1977);
insert into album (id,name,artist,genre,year) values(69,'Currents','Tame Impala','Indie',2015);
insert into album (id,name,artist,genre,year) values(70,'Whirlpool','Chapterhouse','Alternative',1990);
insert into album (id,name,artist,genre,year) values(71,'London Calling','The Clash','Rock',1979);
insert into album (id,name,artist,genre,year) values(72,'Crooked Rain Crooked Rain','Pavement','Alternative',1994);
insert into album (id,name,artist,genre,year) values(73,'The World Won''t End','Pernice Brothers','Indie',2001);
insert into album (id,name,artist,genre,year) values(74,'Recess','Skrillex','Electronica',2014);
insert into album (id,name,artist,genre,year) values(75,'Post','Bj苔rk','Alternative',1995);
insert into album (id,name,artist,genre,year) values(76,'Automatic For the People','R.E.M.','Alternative',1992);
insert into album (id,name,artist,genre,year) values(77,'Heaven Is Whenever','The Hold Steady','Indie',2010);
insert into album (id,name,artist,genre,year) values(78,'Supa Dupa Fly','Missy Elliott','Rap',1997);
insert into album (id,name,artist,genre,year) values(79,'Bitter Rivals','Sleigh Bells','Indie',2013);
insert into album (id,name,artist,genre,year) values(80,'No No No','Beirut','Indie',2015);
insert into album (id,name,artist,genre,year) values(81,'Lights Out','Ingrid Michaelson','Folk',2014);
insert into album (id,name,artist,genre,year) values(82,'V','Maroon 5','Pop',2015);
insert into album (id,name,artist,genre,year) values(83,'Paul Weller','Paul Weller','Alternative',1992);
insert into album (id,name,artist,genre,year) values(84,'Elastica','Elastica','Alternative',1995);
insert into album (id,name,artist,genre,year) values(85,'Love','The Cult','Rock',1985);
insert into album (id,name,artist,genre,year) values(86,'Through the Looking Glass','Siouxsie and the Banshees','New Wave',1987);
insert into album (id,name,artist,genre,year) values(87,'Dirty Heads','Dirty Heads','Reggae',2016);
insert into album (id,name,artist,genre,year) values(88,'Every Open Eye','CHVRCHES','Indie',2016);
insert into album (id,name,artist,genre,year) values(89,'Janet','Janet Jackson','Pop',1993);
insert into album (id,name,artist,genre,year) values(90,'Dangerous','Michael Jackson','Pop',1991);
insert into album (id,name,artist,genre,year) values(91,'II','Led Zeppelin','Rock',1969);
insert into album (id,name,artist,genre,year) values(92,'Heroes','David Bowie','Rock',1977);
insert into album (id,name,artist,genre,year) values(93,'The Smiths','The Smiths','Alternative',1984);
insert into album (id,name,artist,genre,year) values(94,'The Slim Shady LP','Eminem','Rap',1999);
insert into album (id,name,artist,genre,year) values(95,'Underground','Thelonius Monk','Jazz',1968);
insert into album (id,name,artist,genre,year) values(96,'Being There','Wilco','Folk',1996);
insert into album (id,name,artist,genre,year) values(97,'Live!','Bob Marley','Reggae',1975);
insert into album (id,name,artist,genre,year) values(98,'Modern Vampires of the City','Vampire Weekend','Indie',2013);
insert into album (id,name,artist,genre,year) values(99,'Jazz','Queen','Rock',1978);
insert into album (id,name,artist,genre,year) values(100,'Vitalogy','Pearl Jam','Alternative',1994);
insert into album (id,name,artist,genre,year) values(101,'Toto IV','Toto','Yacht Rock',1982);
insert into album (id,name,artist,genre,year) values(102,'Let''s Be Still','The Head and the Heart','Indie',2013);
insert into album (id,name,artist,genre,year) values(103,'Sgt Pepper''s Lonely Hearts Club Band','The Beatles','Rock',1967);